/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppSekolah {
        "id": string;
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLAppSekolahElement extends Components.AppSekolah, HTMLStencilElement {
    }
    var HTMLAppSekolahElement: {
        prototype: HTMLAppSekolahElement;
        new (): HTMLAppSekolahElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-sekolah": HTMLAppSekolahElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppSekolah {
        "id"?: string;
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "app-sekolah": AppSekolah;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-sekolah": LocalJSX.AppSekolah & JSXBase.HTMLAttributes<HTMLAppSekolahElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
